### ISSUE TITLE
Error on startup (dev build)

### ISSUE THREAD

**Issue by jmschonfeld** [CitizensDev/Citizens#135] opened 2011-09-22 11:16 UTC
I have the 1.8 server now, and the update broke the stable build of citizens. The dev build works, except whenevr it finishes loading everything, it repeats "Reached end of stream" about 20-30 times. Is this normal? (I used the stable citizens folder for the dev version. Is that the problem?) Thanks!

**Comment by aPunch** [comment] 2011-09-22 17:25
Please paste the error.

**Comment by defaultsucks** [comment] 2011-09-22 17:50
I get that about two or three times every startup. It just says r"eached end of stream" in the console. I wasn't even sure this was related to citizens until I saw this.

**Comment by aPunch** [comment] 2011-09-22 19:10
Are you sure it is Citizens that is causing this? Have you tried removing Citizens to see if the error is still present?

EDIT - I did some testing and got "Reached end of stream" once with questers installed. Uninstalling them results in none of those messages. Could some else do some extensive testing with different combinations of NPC types to see if they are the cause of this issue, and if so, which ones?

**Comment by jmschonfeld** [comment] 2011-09-22 19:55
Um... The error isn't an actual error. It is Citizens for sure. It just repeats "Reached end of stream" like 20-30 times. Other than that, it works. I have the following types: Guard, Blacksmith, Healer, Trader, and Wizard. Here is what happens:

2011-09-22 07:13:35 [INFO] Done (1.351s)! For help, type "help" or "?"
2011-09-22 07:13:36 [INFO] Reached end of stream
2011-09-22 07:13:36 [INFO] Reached end of stream
2011-09-22 07:13:36 [INFO] Reached end of stream
2011-09-22 07:13:36 [INFO] Reached end of stream
2011-09-22 07:13:36 [INFO] Reached end of stream
2011-09-22 07:13:36 [INFO] Reached end of stream
2011-09-22 07:13:36 [INFO] Reached end of stream
2011-09-22 07:13:36 [INFO] Reached end of stream
2011-09-22 07:13:36 [INFO] Reached end of stream
2011-09-22 07:13:36 [INFO] Reached end of stream
2011-09-22 07:13:36 [INFO] Reached end of stream
2011-09-22 07:13:36 [INFO] Reached end of stream
2011-09-22 07:13:36 [INFO] Reached end of stream
2011-09-22 07:13:36 [INFO] Reached end of stream
2011-09-22 07:13:36 [INFO] Reached end of stream
2011-09-22 07:13:36 [INFO] Reached end of stream
2011-09-22 07:13:36 [INFO] Reached end of stream
2011-09-22 07:13:36 [INFO] Reached end of stream
2011-09-22 07:13:36 [INFO] Reached end of stream
2011-09-22 07:13:36 [INFO] Reached end of stream
2011-09-22 07:13:36 [INFO] Reached end of stream
2011-09-22 07:13:36 [INFO] Reached end of stream
2011-09-22 07:13:36 [INFO] Reached end of stream
2011-09-22 07:13:36 [INFO] Reached end of stream
2011-09-22 07:13:36 [INFO] Reached end of stream
2011-09-22 07:13:36 [INFO] Reached end of stream
2011-09-22 07:13:36 [INFO] Reached end of stream
2011-09-22 07:13:36 [INFO] Reached end of stream
2011-09-22 07:13:36 [INFO] Reached end of stream
2011-09-22 07:13:36 [INFO] Reached end of stream
2011-09-22 07:13:36 [INFO] Reached end of stream
2011-09-22 07:13:36 [INFO] Reached end of stream
2011-09-22 07:13:36 [INFO] Reached end of stream
2011-09-22 07:13:36 [INFO] Reached end of stream
2011-09-22 07:13:36 [INFO] Reached end of stream
2011-09-22 07:13:36 [INFO] Reached end of stream
2011-09-22 07:13:36 [INFO] Reached end of stream
2011-09-22 07:13:36 [INFO] Reached end of stream
2011-09-22 07:13:36 [INFO] Reached end of stream
2011-09-22 07:13:36 [INFO] Reached end of stream
2011-09-22 07:13:36 [INFO] Reached end of stream
2011-09-22 07:13:36 [INFO] Reached end of stream
2011-09-22 07:13:36 [INFO] Reached end of stream
2011-09-22 07:13:36 [INFO] Reached end of stream
2011-09-22 07:13:36 [INFO] Reached end of stream
2011-09-22 07:13:36 [INFO] Reached end of stream
2011-09-22 07:13:36 [INFO] Reached end of stream
2011-09-22 07:13:36 [INFO] Reached end of stream
2011-09-22 07:13:36 [INFO] Reached end of stream
2011-09-22 07:13:36 [INFO] Reached end of stream
2011-09-22 07:13:36 [INFO] Reached end of stream
2011-09-22 07:13:36 [INFO] Reached end of stream
2011-09-22 07:13:36 [INFO] Reached end of stream
2011-09-22 07:13:36 [INFO] Reached end of stream
2011-09-22 07:13:36 [INFO] Reached end of stream
2011-09-22 07:13:36 [INFO] Reached end of stream
2011-09-22 07:13:36 [INFO] Reached end of stream
2011-09-22 07:13:36 [INFO] Reached end of stream
2011-09-22 07:13:36 [INFO] Reached end of stream
2011-09-22 07:13:36 [INFO] Reached end of stream
2011-09-22 07:13:36 [INFO] Reached end of stream
2011-09-22 07:13:36 [INFO] Reached end of stream
2011-09-22 07:13:36 [INFO] Reached end of stream
2011-09-22 07:13:36 [INFO] Reached end of stream
2011-09-22 07:13:36 [INFO] Reached end of stream
2011-09-22 07:13:36 [INFO] [Citizens] Loaded 95 NPCs.

**Comment by jmschonfeld** [comment] 2011-09-23 10:57
I have tried restarting my server a lot, and it just says "reached end of stream" a random amount of times. Usually 5-20 times now

**Comment by footwo** [comment] 2011-09-23 20:51
I can confirm this. Using the latest build off Jenkins. For every NPC I create, I get a [INFO] Reached end of stream error. It also occurs when you create one, like Java is having trouble parsing the file.

Only happens when Citizens is turned on. If you do a fresh install and create no NPC's, it does not error.

**Comment by Spidi** [comment] 2011-09-23 21:37
Yes we are also seeing this :/

**Comment by fullwall** [comment] 2011-09-24 08:19
Hmmm - this looks like a bukkit debug message? NPCs are 'players' - end of stream seems to mean that the packet inputstream has run out - maybe Bukkit is logging the message as if the npc 'players' have lost their 'connection' with the server? Strange, to say the least.

**Comment by jmschonfeld** [comment] 2011-09-24 15:25
Should we report this error on the bukkit issue page? We should make sure it is bukkit and not citizens though. An EndOfStream Exception usually occurs (in minecraft/java) when something is being read or connected to, and the stream gets cut or stopped, like if minecraft crashes while on a multiplayer server, the console gets a message saying: "[info] -name- has left the game: disconnect.EndOfStream". Maybe it "thinks" that the npc's are real players and are trying to get info about them that it cant get because they arent "real" players. (I am new to java so I might be wrong)

**Comment by footwo** [comment] 2011-09-25 01:46
Jeremy, it's not that same error, it's "Reached end of stream" A stream in java doesn't have to be a network connection it can be a file read too.

**Comment by fullwall** [comment] 2011-09-25 03:16
It's a network error. NPCs aren't sending complete packet input streams, causing the 'error'. I'll try to find a fix.

**Comment by fullwall** [comment] 2011-09-25 03:24
Looks like this is a tough one without access to lower-level network methods (which are private unfortunately).

**Comment by aPunch** [comment] 2011-09-25 04:23
Reflection?!

**Comment by fullwall** [comment] 2011-09-25 06:20
Can't reflect-replace methods AFAIK.

**Comment by fullwall** [comment] 2011-09-25 14:35
Can you recheck on latest builds?

**Comment by jmschonfeld** [comment] 2011-09-25 20:35
I take it that you guys are working on the problem because I have no idea what you are saying. Please let me know when/if you get the problem fixed

**Comment by bskjon** [comment] 2011-10-04 11:54
I'm getting that, but it shows often on my server. it appears a while after the load.

**Comment by adambratt** [comment] 2011-10-04 17:29
fullwall: What is making this happen now that wasn't in the past?

It's just with the more recent builds of Citizens I've seen this problem. Hopefully 1.9 will provide a way to differentiate between a player and an NPC given that minecraft will now naturally produce NPCs.

**Comment by bskjon** [comment] 2011-10-04 19:00
Right........ Now we got the npc following us and they push us in one direction

**Comment by jmschonfeld** [comment] 2011-10-04 19:40
Now that the new CB RB has come out, I will see if this fixes it. It mioght considering they added to the change log:
" ADDED: New packet handling"
and fullwall said:
"NPCs aren't sending complete packet input streams"
I am testing right now to see if it fixes it. (with citizens version 1.1.1)
Standby for results...

RESULTS:
The new craftbukkit recommended build did NOT fix the "Reached End of Stream" error

**Comment by adambratt** [comment] 2011-10-04 21:25
darn it.

**Comment by fullwall** [comment] 2011-10-07 05:40
Fixed in newest builds.

**Closed as completed by fullwall** 2011-10-07 05:40 UTC
Labels: Bug

**Comment by jmschonfeld** [comment] 2011-10-07 19:29
Newest builds of Bukkit or citizens?
